# Generated by Django 4.2.7 on 2023-11-28 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('singer', models.CharField(max_length=100)),
                ('length', models.IntegerField()),
                ('poster', models.ImageField(upload_to='ConcertImages/')),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=13)),
                ('capacity', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profile_image', models.ImageField(null=True, upload_to='ProfileImages/')),
                ('gender', models.IntegerField(choices=[('Man', 'Male'), ('Woman', 'Female')])),
            ],
        ),
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField()),
                ('seats', models.IntegerField()),
                ('status', models.IntegerField(choices=[('Start', 'Ticket sales have started'), ('Selling', 'Ticket selling'), ('Cancel', 'This screening has been cancelled'), ('End', 'Ticket sales have ended')])),
                ('concert', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.concert')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.location')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('ticket_images', models.ImageField(upload_to='TicketImages/')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.profile')),
                ('time', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.time')),
            ],
        ),
    ]
