# Generated by Django 4.2.7 on 2023-12-04 14:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='concert',
            options={'verbose_name': 'کنسرت', 'verbose_name_plural': 'کنسرت'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'verbose_name': 'محل برگزاری', 'verbose_name_plural': 'محل برگزاری'},
        ),
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'کاربر', 'verbose_name_plural': 'کاربر'},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'verbose_name': 'بلیط', 'verbose_name_plural': 'بلیط'},
        ),
        migrations.AlterModelOptions(
            name='time',
            options={'verbose_name': 'سانس', 'verbose_name_plural': 'سانس'},
        ),
        migrations.AlterField(
            model_name='concert',
            name='name',
            field=models.CharField(max_length=100, null=True, verbose_name='نام کنسرت'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='poster',
            field=models.ImageField(upload_to='ConcertImages/', verbose_name='پوستر'),
        ),
        migrations.AlterField(
            model_name='concert',
            name='singer',
            field=models.CharField(max_length=100, verbose_name='خواننده'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address',
            field=models.CharField(max_length=300, verbose_name='آدرس'),
        ),
        migrations.AlterField(
            model_name='location',
            name='capacity',
            field=models.IntegerField(verbose_name='ظرفیت'),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=50, verbose_name='نام محل'),
        ),
        migrations.AlterField(
            model_name='location',
            name='phone',
            field=models.CharField(max_length=13, verbose_name='تلفن'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(max_length=50, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.IntegerField(choices=[('Man', 'مرد'), ('Woman', 'زن')], verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(max_length=50, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(null=True, upload_to='ProfileImages/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='name',
            field=models.CharField(max_length=100, verbose_name='عنوان'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='price',
            field=models.IntegerField(verbose_name='مبلغ'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.profile', verbose_name='کاربر'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='ticket_images',
            field=models.ImageField(upload_to='TicketImages/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.time', verbose_name='سانس'),
        ),
        migrations.AlterField(
            model_name='time',
            name='concert',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.concert', verbose_name='کنسرت'),
        ),
        migrations.AlterField(
            model_name='time',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tickets.location', verbose_name='محل برگزاری'),
        ),
        migrations.AlterField(
            model_name='time',
            name='seats',
            field=models.IntegerField(verbose_name='تعداد صندلی ها'),
        ),
        migrations.AlterField(
            model_name='time',
            name='start',
            field=models.DateTimeField(verbose_name='تاریخ برگزاری'),
        ),
        migrations.AlterField(
            model_name='time',
            name='status',
            field=models.IntegerField(choices=[(1, 'فروش بلیط شروع شده است'), (2, 'در حال فروش بلیط'), (3, 'این سانس لغو شده است'), (4, 'فروش بلیط پایان یافته است')], verbose_name='وضعیت'),
        ),
    ]
