# Generated by Django 4.2.7 on 2023-12-11 02:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('tickets', '0002_alter_concert_options_alter_location_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.profile', verbose_name='کاربر'),
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
